make:
	@echo make delete to delete files
	@echo make submit to delete files and this Makefile

delete:
	make -C ex00 fclean
	make -C ex01 fclean
	make -C ex02 fclean
	make -C ex03 fclean

submit: delete
	rm -f Makefile